### ISSUE TITLE
I can't create a LoadBalancer in Kubernetes Cluster

### ISSUE THREAD

**Issue by pasqualet** [cloud-toolkit/cloud-toolkit-aws#85]
**Describe the bug**

I can't create a LoadBalancer in Kubernetes Cluster.

**To Reproduce**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

**Expected behavior**

The LoadBalancer should be created.

**Actual behavior**

The LoadBalancer is stuck in Pending state.

```bash
$ get svc nginx-service
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
nginx-service   LoadBalancer   10.100.32.48   <pending>     9090:32302/TCP   8h
```

**Output of `pulumi about`**

cloud-toolkit 0.4.1
